name: e2e
on:
  workflow_dispatch:         # run it manually
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      CI: true
      BASE_URL: https://www.mybabyfits.com
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci || npm install

      # Installs Playwright browsers & OS deps on Ubuntu
      - uses: microsoft/playwright-github-action@v1

      # Run a fast, reliable slice first. Switch to all browsers later.
      - name: Run Playwright tests (Chromium)
        run: npx playwright test --project=chromium --reporter=list,html

      # Always upload the HTML report, even if tests failed
      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore
