name: e2e
on:
  workflow_dispatch:   # manual run button on GitHub
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BASE_URL: https://www.mybabyfits.com
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm ci || npm install
      - run: npx playwright install --with-deps
      - run: npx playwright test --reporter=html
      - uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
